<CONSTANTE> : constantes
<IDENT> : PI
<OP-ASIG> : :=
<CTE-REAL> : 3.141592
<PUNTO_COMA> : ;
<IDENT> : MAX
<OP-ASIG> : :=
<CTE-ENTERA> : 30
<PUNTO_COMA> : ;
<VARIABLES> : variables
<IDENT> : k
<PUNTOS_DOBLES> : :
<TIPO> : Entero
<PUNTO_COMA> : ;
<IDENT> : Alfa
<COMA> : ,
<IDENT> : Beta
<PUNTOS_DOBLES> : :
<TIPO> : Alfabetico
<PUNTO_COMA> : ;
<PROTOTIPOS> : Prototipos
<FIN> : Fin
<DE> : de
<PROTOTIPOS> : Prototipos
<PUNTO_COMA> : ;
<PROCEDIMIENTO> : Procedimiento
<IDENT> : Selecciona
<PAREN_EMPIEZA> : (
<PAREN_TERMINA> : )
<VARIABLES> : variables
<IDENT> : opc
<PUNTOS_DOBLES> : :
<TIPO> : alfabetico
<PUNTO_COMA> : ;
<INICIO> : Inicio
<IMPRIME> : Imprime
<PAREN_EMPIEZA> : (
<CTE-ALFA> : "Te gustan las matematicas? (S,s), (N, n) "
<PAREN_TERMINA> : )
<PUNTO_COMA> : ;
<LEE> : Lee
<PAREN_EMPIEZA> : (
<IDENT> : opc
<PAREN_TERMINA> : )
<PUNTO_COMA> : ;
<CUANDO> : Cuando
<EL> : el
<VALOR> : valor
<DE> : de
<IDENT> : opc
<INICIO> : Inicio
<SEA> : Sea
<CTE-ALFA> : "S"
<COMA> : ,
<CTE-ALFA> : "s"
<PUNTOS_DOBLES> : :
<IMPRIMENL> : imprimenl
<PAREN_EMPIEZA> : (
<CTE-ALFA> : "Bien, eres un suertudo"
<PAREN_TERMINA> : )
<SEA> : Sea
<CTE-ALFA> : "N"
<COMA> : ,
<CTE-ALFA> : "n"
<PUNTOS_DOBLES> : :
<IMPRIMENL> : imprimenl
<PAREN_EMPIEZA> : (
<CTE-ALFA> : "A mi tampoco"
<PAREN_TERMINA> : )
<OTRO> : Otro
<PUNTOS_DOBLES> : :
<IMPRIMENL> : Imprimenl
<PAREN_EMPIEZA> : (
<CTE-ALFA> : "Bien! No caes en esta falsa dicotomia"
<PAREN_TERMINA> : )
<FIN> : Fin
<PUNTO_COMA> : ;
<FIN> : Fin
<DE> : de
<PROCEDIMIENTO> : Procedimiento
<PUNTO_COMA> : ;
<PROGRAMA> : Programa
<LEE> : Lee
<PAREN_EMPIEZA> : (
<IDENT> : Alfa
<PAREN_TERMINA> : )
<PUNTO_COMA> : ;
<IMPRIMENL> : Imprimenl
<PAREN_EMPIEZA> : (
<IDENT> : Beta
<PAREN_TERMINA> : )
<PUNTO_COMA> : ;
<IMPRIMENL> : Imprimenl
<PAREN_EMPIEZA> : (
<IDENT> : k
<PAREN_TERMINA> : )
<PUNTO_COMA> : ;
<FIN> : Fin
<DE> : de
<PROGRAMA> : programa
<PUNTO> : .
