<CONSTANTE> : Constantes
<IDENT> : a
<OP-ASIG> : :=
<CTE-ENTERA> : 2
<PUNTO_COMA> : ;
<VARIABLES> : Variables
<IDENT> : opc
<COMA> : ,
<IDENT> : beta
<PUNTOS_DOBLES> : :
<TIPO> : Alfabetico
<PUNTO_COMA> : ;
<PROTOTIPOS> : Prototipos
<FIN> : Fin
<DE> : de
<PROTOTIPOS> : Prototipos
<PUNTO_COMA> : ;
<PROGRAMA> : Programa
<IMPRIMENL> : Imprimenl
<PAREN_EMPIEZA> : (
<CTE-ALFA> : "PASAMOS?(sS/nN)"
<PAREN_TERMINA> : )
<PUNTO_COMA> : ;
<LEE> : Lee
<PAREN_EMPIEZA> : (
<IDENT> : beta
<PAREN_TERMINA> : )
<PUNTO_COMA> : ;
<FIN> : Fin
<DE> : de
<PROGRAMA> : programa
<PUNTO> : .
