<CONSTANTE> : constantes
<IDENT> : PI
<OP-ASIG> : :=
<CTE-REAL> : 3.141592
<PUNTO_COMA> : ;
<IDENT> : MAX
<OP-ASIG> : :=
<CTE-ENTERA> : 30
<PUNTO_COMA> : ;
<VARIABLES> : variables
<IDENT> : i
<COMA> : ,
<IDENT> : j
<COMA> : ,
<IDENT> : k
<COMA> : ,
<IDENT> : n
<PUNTOS_DOBLES> : :
<TIPO> : Entero
<PUNTO_COMA> : ;
<IDENT> : Alfa
<COMA> : ,
<IDENT> : Beta
<COMA> : ,
<IDENT> : opc
<PUNTOS_DOBLES> : :
<TIPO> : alfabetico
<PUNTO_COMA> : ;
<PROTOTIPOS> : Prototipos
<FIN> : Fin
<DE> : de
<PROTOTIPOS> : Prototipos
<PUNTO_COMA> : ;
<PROGRAMA> : Programa
<IMPRIME> : Imprime
<PAREN_EMPIEZA> : (
<CTE-ALFA> : "Dame un numero: "
<PAREN_TERMINA> : )
<PUNTO_COMA> : ;
<LEE> : lee
<PAREN_EMPIEZA> : (
<IDENT> : n
<PAREN_TERMINA> : )
<PUNTO_COMA> : ;
<REPETIR> : Repetir
<IMPRIMENL> : Imprimenl
<PAREN_EMPIEZA> : (
<CTE-ALFA> : "Factorial R]ecursivo I]nteractivo S]alir: "
<PAREN_TERMINA> : )
<PUNTO_COMA> : ;
<LEE> : Lee
<PAREN_EMPIEZA> : (
<IDENT> : opc
<PAREN_TERMINA> : )
<PUNTO_COMA> : ;
<CUANDO> : Cuando
<EL> : el
<VALOR> : valor
<DE> : de
<IDENT> : opc
<INICIO> : Inicio
<SEA> : Sea
<CTE-ALFA> : "R"
<COMA> : ,
<CTE-ALFA> : "r"
<PUNTOS_DOBLES> : :
<IMPRIMENL> : imprimenl
<PAREN_EMPIEZA> : (
<CTE-ALFA> : "Factorial Recursivo de "
<COMA> : ,
<IDENT> : n
<COMA> : ,
<CTE-ALFA> : " es= "
<COMA> : ,
<IDENT> : n
<PAREN_TERMINA> : )
<SEA> : Sea
<CTE-ALFA> : "I"
<COMA> : ,
<CTE-ALFA> : "i"
<PUNTOS_DOBLES> : :
<IMPRIMENL> : imprimenl
<PAREN_EMPIEZA> : (
<CTE-ALFA> : "Factorial Iterativo de "
<COMA> : ,
<IDENT> : n
<COMA> : ,
<COMA> : ,
<CTE-ALFA> : "no lo se"
<PAREN_TERMINA> : )
<OTRO> : Otro
<PUNTOS_DOBLES> : :
<IMPRIMENL> : Imprimenl
<PAREN_EMPIEZA> : (
<CTE-ALFA> : "Opcion Invalida!!!"
<PAREN_TERMINA> : )
<FIN> : Fin
<PUNTO_COMA> : ;
<HASTA> : hasta
<QUE> : que
<PAREN_EMPIEZA> : (
<IDENT> : opc
<OP-REL> : =
<CTE-ALFA> : "S"
<O> : o
<IDENT> : opc
<OP-REL> : =
<CTE-ALFA> : "s"
<PAREN_TERMINA> : )
<PUNTO_COMA> : ;
<FIN> : Fin
<DE> : de
<PROGRAMA> : programa
<PUNTO> : .
