<CONSTANTE> : constantes
<IDENT> : PI
<OP-ASIG> : :=
<CTE-REAL> : 3.141592
<PUNTO_COMA> : ;
<IDENT> : MAX
<OP-ASIG> : :=
<CTE-ENTERA> : 30
<PUNTO_COMA> : ;
<VARIABLES> : variables
<IDENT> : i
<COMA> : ,
<IDENT> : j
<COMA> : ,
<IDENT> : k
<COMA> : ,
<IDENT> : n
<PUNTOS_DOBLES> : :
<TIPO> : Entero
<PUNTO_COMA> : ;
<IDENT> : Alfa
<COMA> : ,
<IDENT> : Beta
<PUNTOS_DOBLES> : :
<TIPO> : Alfabetico
<PUNTO_COMA> : ;
<PROTOTIPOS> : Prototipos
<FUNCION> : Funcion
<IDENT> : FacRec
<PAREN_EMPIEZA> : (
<IDENT> : n
<PUNTOS_DOBLES> : :
<TIPO> : Entero
<PAREN_TERMINA> : )
<PUNTOS_DOBLES> : :
<TIPO> : Entero
<PUNTO_COMA> : ;
<FUNCION> : Funcion
<IDENT> : FacIter
<PAREN_EMPIEZA> : (
<IDENT> : n
<PUNTOS_DOBLES> : :
<TIPO> : Entero
<PAREN_TERMINA> : )
<PUNTOS_DOBLES> : :
<TIPO> : Entero
<PUNTO_COMA> : ;
<FIN> : Fin
<DE> : de
<PROTOTIPOS> : Prototipos
<PUNTO_COMA> : ;
<PROCEDIMIENTO> : Procedimiento
<IDENT> : Selecciona
<PAREN_EMPIEZA> : (
<PAREN_TERMINA> : )
<VARIABLES> : variables
<IDENT> : opc
<PUNTOS_DOBLES> : :
<TIPO> : alfabetico
<PUNTO_COMA> : ;
<INICIO> : Inicio
<IMPRIME> : Imprime
<PAREN_EMPIEZA> : (
<CTE-ALFA> : "Dame un numero: "
<PAREN_TERMINA> : )
<PUNTO_COMA> : ;
<LEE> : lee
<PAREN_EMPIEZA> : (
<IDENT> : n
<PAREN_TERMINA> : )
<PUNTO_COMA> : ;
<REPETIR> : Repetir
<IMPRIME> : Imprime
<PAREN_EMPIEZA> : (
<CTE-ALFA> : "Factorial R]ecursivo I]nteractivo S]alir: "
<PAREN_TERMINA> : )
<PUNTO_COMA> : ;
<LEE> : Lee
<PAREN_EMPIEZA> : (
<IDENT> : opc
<PAREN_TERMINA> : )
<PUNTO_COMA> : ;
<CUANDO> : Cuando
<EL> : el
<VALOR> : valor
<DE> : de
<IDENT> : opc
<INICIO> : Inicio
<SEA> : Sea
<CTE-ALFA> : "R"
<COMA> : ,
<CTE-ALFA> : "r"
<PUNTOS_DOBLES> : :
<IMPRIMENL> : imprimenl
<PAREN_EMPIEZA> : (
<CTE-ALFA> : "Factorial Recursivo de "
<COMA> : ,
<IDENT> : n
<COMA> : ,
<CTE-ALFA> : " es= "
<COMA> : ,
<IDENT> : FacRec
<PAREN_EMPIEZA> : (
<IDENT> : n
<PAREN_TERMINA> : )
<PAREN_TERMINA> : )
<SEA> : Sea
<CTE-ALFA> : "I"
<COMA> : ,
<CTE-ALFA> : "i"
<PUNTOS_DOBLES> : :
<IMPRIMENL> : imprimenl
<PAREN_EMPIEZA> : (
<CTE-ALFA> : "Factorial Iterativo de "
<COMA> : ,
<IDENT> : n
<COMA> : ,
<COMA> : ,
<IDENT> : FacIter
<PAREN_EMPIEZA> : (
<IDENT> : n
<PAREN_TERMINA> : )
<PAREN_TERMINA> : )
<OTRO> : Otro
<PUNTOS_DOBLES> : :
<SI> : Si
<PAREN_EMPIEZA> : (
<IDENT> : opc
<OP-REL> : <>
<CTE-ALFA> : "S"
<Y> : y
<IDENT> : opc
<OP-REL> : <>
<CTE-ALFA> : "s"
<PAREN_TERMINA> : )
<HACER> : hacer
<IMPRIMENL> : Imprimenl
<PAREN_EMPIEZA> : (
<CTE-ALFA> : "Opcion Invalida!!!"
<PAREN_TERMINA> : )
<FIN> : Fin
<PUNTO_COMA> : ;
<HASTA> : hasta
<QUE> : que
<PAREN_EMPIEZA> : (
<IDENT> : opc
<OP-REL> : =
<O> : o
<IDENT> : opc
<OP-REL> : =
<PAREN_TERMINA> : )
<PUNTO_COMA> : ;
<FIN> : Fin
<DE> : de
<PROCEDIMIENTO> : Procedimiento
<PUNTO_COMA> : ;
<FUNCION> : Funcion
<IDENT> : FacRec
<PAREN_EMPIEZA> : (
<IDENT> : n
<PUNTOS_DOBLES> : :
<TIPO> : entero
<PAREN_TERMINA> : )
<PUNTOS_DOBLES> : :
<TIPO> : Entero
<INICIO> : Inicio
<SI> : Si
<PAREN_EMPIEZA> : (
<IDENT> : n
<OP-REL> : <
<CTE-ENTERA> : 2
<PAREN_TERMINA> : )
<HACER> : hacer
<REGRESA> : regresa
<PAREN_EMPIEZA> : (
<CTE-ENTERA> : 1
<PAREN_TERMINA> : )
<SINO> : sino
<REGRESA> : regresa
<PAREN_EMPIEZA> : (
<IDENT> : FacRec
<PAREN_EMPIEZA> : (
<IDENT> : n
<MENOS> : -
<CTE-ENTERA> : 1
<PAREN_TERMINA> : )
<MULTI> : *
<IDENT> : n
<PAREN_TERMINA> : )
<PUNTO_COMA> : ;
<FIN> : Fin
<DE> : de
<FUNCION> : Funcion
<PUNTO_COMA> : ;
<FUNCION> : Funcion
<IDENT> : FacIter
<PAREN_EMPIEZA> : (
<IDENT> : n
<PUNTOS_DOBLES> : :
<TIPO> : Entero
<PAREN_TERMINA> : )
<PUNTOS_DOBLES> : :
<TIPO> : Entero
<VARIABLES> : Variables
<IDENT> : Facto
<PUNTOS_DOBLES> : :
<TIPO> : Entero
<PUNTO_COMA> : ;
<INICIO> : Inicio
<IDENT> : Facto
<OP-ASIG> : :=
<CTE-ENTERA> : 1
<PUNTO_COMA> : ;
<DESDE> : Desde
<EL> : el
<VALOR> : valor
<DE> : de
<IDENT> : i
<OP-ASIG> : :=
<IDENT> : n
<HASTA> : hasta
<CTE-ENTERA> : 2
<DECR> : decr
<CTE-ENTERA> : 1
<IDENT> : Facto
<OP-ASIG> : :=
<IDENT> : Facto
<MULTI> : *
<IDENT> : i
<PUNTO_COMA> : ;
<REGRESA> : regresa
<PAREN_EMPIEZA> : (
<IDENT> : facto
<PAREN_TERMINA> : )
<PUNTO_COMA> : ;
<FIN> : Fin
<DE> : de
<FUNCION> : Funcion
<PUNTO_COMA> : ;
<PROGRAMA> : Programa
<LIMPIA> : limpia
<PUNTO_COMA> : ;
<IDENT> : k
<OP-ASIG> : :=
<CTE-ENTERA> : 3
<PUNTO_COMA> : ;
<IDENT> : Selecciona
<PAREN_EMPIEZA> : (
<PAREN_TERMINA> : )
<PUNTO_COMA> : ;
<LEE> : Lee
<PAREN_EMPIEZA> : (
<IDENT> : alfa
<PAREN_TERMINA> : )
<PUNTO_COMA> : ;
<IDENT> : beta
<OP-ASIG> : :=
<CTE-ALFA> : "Villalvazo"
<PUNTO_COMA> : ;
<IMPRIMENL> : Imprimenl
<PAREN_EMPIEZA> : (
<IDENT> : beta
<PAREN_TERMINA> : )
<PUNTO_COMA> : ;
<IMPRIMENL> : Imprimenl
<PAREN_EMPIEZA> : (
<IDENT> : k
<PAREN_TERMINA> : )
<PUNTO_COMA> : ;
<FIN> : Fin
<DE> : de
<PROGRAMA> : programa
<PUNTO> : .
